languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Home"
copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"
  mainSections = ["notes"]
  description = "Notes from culinary adventures."


